### ISSUE TITLE
Conflict with Cocoa Async socket

### ISSUE THREAD

**Issue by rajathk** [Catapush/catapush-ios-sdk-pod#1]
I am using a library called NHNetworkTime, this uses Cocoa Async Socket and I get these kind of errors when I make a build-

/Users/rajath/Library/Developer/Xcode/DerivedData/StreetReader-fslwtamovuikbaachjipdrubnatx/Build/Products/Debug-iphoneos/CocoaAsyncSocket/libCocoaAsyncSocket.a(GCDAsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_GCDAsyncSocket.stateIndex in:
   Pods/catapush-ios-sdk-pod/CatapushKit/libCatapushLib.a(GCDAsyncSocket.o)

**Comment by davidemarrone** [comment]
Old issue
